### ISSUE TITLE
Kbase ModelSeed 

### ISSUE THREAD

**Issue by pg42866** [BioSystemsUM/mewpy#16]
Boa tarde,
Envio em anexo o modelo metabólico obtido pela app modelSeed na kbase, o qual segundo o FBA da plataforma indica um fluxo de biomassa de cerca de 19 em meio completo. Contudo, o mewpy indica "None" quando o objetivo definido é a biomassa.
[M_formicicum_complete_media.SBML (1).zip](https://github.com/BioSystemsUM/mewpy/files/6604418/M_formicicum_complete_media.SBML.1.zip)

![image](https://user-images.githubusercontent.com/73937757/120930398-f9c1c180-c6e4-11eb-8bb8-5bf3a80d90eb.png)

**Comment by pg42866** [comment]
Acrescento ainda informação completar de acordo com os resultados obtidos no CobraPy, obrigado pela atenção.

M_formicicum_complete_media
62.564878115599804
Objective
=========
1.0 bio1_biomass = 62.564878115599804

Uptake
------
 Metabolite       Reaction   Flux  C-Number C-Flux
cpd00006_e0 EX_cpd00006_e0 0.3511        21  0.16%
cpd00007_e0 EX_cpd00007_e0  643.9         0  0.00%
cpd00009_e0 EX_cpd00009_e0   45.2         0  0.00%
cpd00010_e0 EX_cpd00010_e0 0.3511        21  0.16%
cpd00017_e0 EX_cpd00017_e0  17.72        15  5.65%
cpd00023_e0 EX_cpd00023_e0  30.91         5  3.28%
cpd00027_e0 EX_cpd00027_e0  208.4         6 26.57%
cpd00028_e0 EX_cpd00028_e0 0.1756        34  0.13%
cpd00030_e0 EX_cpd00030_e0 0.1756         0  0.00%
cpd00033_e0 EX_cpd00033_e0  30.85         2  1.31%
cpd00034_e0 EX_cpd00034_e0 0.1756         0  0.00%
cpd00035_e0 EX_cpd00035_e0  28.34         3  1.81%
cpd00039_e0 EX_cpd00039_e0  17.86         6  2.28%
cpd00041_e0 EX_cpd00041_e0  345.7         4 29.39%
cpd00048_e0 EX_cpd00048_e0 0.1756         0  0.00%
cpd00051_e0 EX_cpd00051_e0  15.43         6  1.97%
cpd00054_e0 EX_cpd00054_e0  14.41         3  0.92%
cpd00058_e0 EX_cpd00058_e0 0.1756         0  0.00%
cpd00063_e0 EX_cpd00063_e0 0.1756         0  0.00%
cpd00065_e0 EX_cpd00065_e0  2.953        11  0.69%
cpd00066_e0 EX_cpd00066_e0  9.667         9  1.85%
cpd00067_e0 EX_cpd00067_e0  89.46         0  0.00%
cpd00069_e0 EX_cpd00069_e0   7.55         9  1.44%
cpd00084_e0 EX_cpd00084_e0   4.94         3  0.31%
cpd00099_e0 EX_cpd00099_e0 0.1756         0  0.00%
cpd00104_e0 EX_cpd00104_e0 0.1756        10  0.04%
cpd00107_e0 EX_cpd00107_e0  23.49         6  3.00%
cpd00118_e0 EX_cpd00118_e0 0.1756         4  0.01%
cpd00119_e0 EX_cpd00119_e0  4.959         6  0.63%
cpd00129_e0 EX_cpd00129_e0  11.53         5  1.23%
cpd00132_e0 EX_cpd00132_e0  12.56         4  1.07%
cpd00136_e0 EX_cpd00136_e0 0.1756         7  0.03%
cpd00149_e0 EX_cpd00149_e0 0.1756         0  0.00%
cpd00156_e0 EX_cpd00156_e0  22.04         5  2.34%
cpd00161_e0 EX_cpd00161_e0  13.21         4  1.12%
cpd00185_e0 EX_cpd00185_e0  4.694         5  0.50%
cpd00205_e0 EX_cpd00205_e0 0.1756         0  0.00%
cpd00216_e0 EX_cpd00216_e0 0.3511        10  0.07%
cpd00220_e0 EX_cpd00220_e0 0.5267        17  0.19%
cpd00254_e0 EX_cpd00254_e0 0.1756         0  0.00%
cpd00264_e0 EX_cpd00264_e0 0.1756         7  0.03%
cpd00305_e0 EX_cpd00305_e0 0.1756        12  0.04%
cpd00322_e0 EX_cpd00322_e0  15.13         6  1.93%
cpd00357_e0 EX_cpd00357_e0  1.178        10  0.25%
cpd00393_e0 EX_cpd00393_e0 0.5267        19  0.21%
cpd00731_e0 EX_cpd00731_e0  1.565         6  0.20%
cpd01741_e0 EX_cpd01741_e0  1.565        12  0.40%
cpd03847_e0 EX_cpd03847_e0  7.824        14  2.33%
cpd10515_e0 EX_cpd10515_e0 0.5267         0  0.00%
cpd15311_e0 EX_cpd15311_e0  7.794        39  6.46%
cpd17041_c0    rxn13782_c0  62.56         0  0.00%
cpd17042_c0    rxn13783_c0  62.56         0  0.00%
cpd17043_c0    rxn13784_c0  62.56         0  0.00%

Secretion
---------
 Metabolite       Reaction   Flux  C-Number C-Flux
cpd11416_c0 DM_cpd11416_c0 -62.56         0  0.00%
cpd00001_e0 EX_cpd00001_e0 -838.8         0  0.00%
cpd00011_e0 EX_cpd00011_e0  -1000         1 44.64%
cpd00013_e0 EX_cpd00013_e0 -280.8         0  0.00%
cpd00029_e0 EX_cpd00029_e0 -588.5         2 52.54%
cpd00047_e0 EX_cpd00047_e0 -7.538         1  0.34%
cpd00060_e0 EX_cpd00060_e0 -9.549         5  2.13%
cpd00116_e0 EX_cpd00116_e0 -7.714         1  0.34%

**Comment by vmspereira** [comment]
Olá pg42866,

Sugiro que em vez de carregar o modelo com o REFRAMED utilize o COBRApy. O REFRAMED pode ter tido alguma dificuldade em ler o modelo. 
Assim, a única alteração que terá de realizar no código em exemplo será, 

```
from cobra.io import read_sbml_model
model = read_sbml_model(PATH_TO_MODEL)

```
em vez de: 

```
from reframed.io.sbml import load_cbmodel
model = load_cbmodel(PATH_TO_MODEL,flavor='cobra')
```

Se de facto tiver preferência em utilizar o REFRAMED, poderá tentar carregar o modelo sem o parâmetro _flavor='cobra'_ ou bem consultar a documentação do REFRAMED em https://reframed.readthedocs.io.
