### ISSUE TITLE
Error in loading GECKO Model

### ISSUE THREAD

**Issue by jinb88187** [BioSystemsUM/mewpy#2]
Hi,

Following your tutorial for enzymatic constraints, I get error for loading GECKO model: "KeyError: 'model name must be one of ", using either the provided model in the repository or an external model. The path to the .xml file is also correct. 

Thanks.

**Comment by vmspereira** [comment]
Hi,

Thank you for pointing the issue. I have updated MEWpy on PyPi with a new version that solves the problem.
You may update from PyPi using the command line:  _pip install mewpy --upgrade_
Thank you again.
