### ISSUE TITLE
error run OptRAM

### ISSUE THREAD

**Issue by maozhitao** [BioSystemsUM/mewpy#21]
I ran the example of OptRAM in the documentation (https://mewpy.readthedocs.io/en/latest/problems.html) and the examples in the code (the two codes are slightly different), both runs resulted in errors, what is the reason?
![20220107095304](https://user-images.githubusercontent.com/3759962/148479335-352ad27e-196d-4741-8a19-1c5d9c1a7fce.png)

**Comment by vmspereira** [comment]
Hi, 

This error occurs during the simplification of the final solutions, which involves an encoding and decoding process of solutions. This might always be possible and it is the reason for the error. You might want to run the optimization process without simplifying the final solutions, that is, passing the no simplify parameter when running the EA:  `final_pop= ea.run(simplify=False)`.

If you have any additional questions please let me know.

**Comment by vmspereira** [comment]
On this issue, the MEWpy version available in the devel branch will skip the simplification of solutions that result in errors, simplifying the remaining ones. Please do not set the simplify flag to False for such a result, as it would not perform simplifications on any of the solutions.
