### ISSUE TITLE
GKOProblem problem

### ISSUE THREAD

**Issue by maozhitao** [BioSystemsUM/mewpy#23]
For the GKOProblem problem, it takes too long to calculate essential genes ( for iML1515 model), so why not just use the find_essential_genes function in the COBRApy, which gets results in seconds.
![image](https://user-images.githubusercontent.com/3759962/149945471-5dd52bf8-b559-43b4-be1d-3682c30287ab.png)

**Comment by vmspereira** [comment]
Before addressing your question, I will take the time to clarify some aspects that I consider important.

- MEWpy is designed to allow the use of distinct phenotypic simulation tools. Presently it encompasses interfaces for REFRAMED, MEW (our own phenotypic simulation tool) and COBRApy. As such, only what is considered essential from each of those frameworks are wrapped by a common interface. 
- MEWpy makes available a set of strain design optimization techniques based on evolutionary combinatorial optimization. Evolutionary computation algorithms, and in particular Evolutionary algorithms, have advantages and disadvantages. The main advantages, I would point out, are 1) their capacity to handle multi-objective optimization problems where the objectives do not need to be linear or quadratic functions and 2) they make no assumption about the regularity of the search space (potentially large). In fact, and contrasting with LP formulations, any function may be used to assess the fitness of solutions. This comes however with what some might identify as disadvantages:  their stochasticity and time-consuming. 
- Although MEWpy might be used in a personal computer, it is specifically designed for long computations in HPCs. MEWpy presently uses multithreading on the optimizations tasks (e.g. using pathos, dask, spark or ray) and we are working on parallelizing others.  

In this context, and addressing what you identified as a "problem", if time is a concern to you, I discourage the use of MEWPy. The parallelisation of genes essentiality computation has not yet been concluded as it is not a priority. Indeed, in the context of large optimizations, which for example might use 100 threads for a week, the few minutes required by sequential gene essentiality analysis seems meaningless.
 
Besides the justification identified above regarding the limited utilization of some frameworks' features, and in the particular case of COBRApy, its API is frequently altered which hinders our capacity to maintain compatibility. 

Nonetheless, I expect that in the near weeks the gene essentiality task, and others, will be parallelized.

Best regards

**Comment by maozhitao** [comment]
Thank you very much for such a detailed reply.
