### ISSUE TITLE
Error in (from mewpy.regulation.optram import OptRamProblem, load_optram)

### ISSUE THREAD

**Issue by jinb88187** [BioSystemsUM/mewpy#3]
Hi, I see the following error:

~\anaconda3\lib\site-packages\mewpy\simulation\cobra.py in <module>
      4 from cobra.core.model import Model
      5 from cobra.core.solution import Solution
----> 6 from geckopy.gecko import GeckoModel
      7 from cobra.flux_analysis import pfba, moma, room
      8 from mewpy.simulation import SimulationMethod, SStatus

ModuleNotFoundError: No module named 'geckopy'

Thanks.

**Comment by vmspereira** [comment]
Hi,

You need to install geckopy (pip install geckopy) to use the original GECKO model implementation by Benjamin Sanchez.
