### ISSUE TITLE
Error in (from mewpy.problems import GeckoROUProblem)

### ISSUE THREAD

**Issue by jinb88187** [BioSystemsUM/mewpy#4]
Hi, I see the following error message:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-11-97df595b40f1> in <module>
     16 
     17 # build a new problem instance for enzymatic OU
---> 18 from mewpy.problems import GeckoROUProblem
     19 problem = GeckoROUProblem(model, fevaluation=[
     20                          evaluator_1, evaluator_2], envcond=envcond)

ImportError: cannot import name 'GeckoROUProblem' from 'mewpy.problems' (C:\Users\anaconda3\lib\site-packages\mewpy\problems\__init__.py)

Thanks.

**Comment by vmspereira** [comment]
You are referring to an older version of MEWpy. You should use GeckoOUProblem instead of  GeckoROUProblem.
