### ISSUE TITLE
ROU optimization

### ISSUE THREAD

**Issue by Laminsecin** [BioSystemsUM/MEWpy#43]
Hi, 

I wanted to ask what the numbers in front of reactions in the modification part actually mean?
![image](https://github.com/BioSystemsUM/MEWpy/assets/119654790/cb62ef2a-f205-4ae3-ade3-997e8defbd1b)

**Comment by vmspereira** [comment]
Hi @Laminsecin 

Over (under)-expressions are modeled by changing the reactions' lower (upper) bound to a factor of a reference distribution of flux values. The numbers in front of each reaction are the applied factors (folds). 

Let us suppose, for example, that the reference flux rate value for the R_ACGH reaction is 0.1 and that the reaction bounds (irreversible reaction) are $$0 \leq R_ACGH \leq 1000.$$ 
The 32, meaning an overexpression of 32 folds, will modify the reaction bounds to 
$$32\times 0.1 \leq R_ACGH \leq 1000,$$ 
forcing a higher flux rate for the R_ACGH reaction. Down regulations, with factors in the ]0,1[ range, will modify the reaction upper bound, causing a reaction flux rate lower than the reference one. 

The user can provide the reference flux distribution as a dictionary of reaction_id, flux value mapping. If none is given, the flux distribution obtained when running a parsimonious FBA for the model objective will be considered. The fold values are configurable and may be any discrete list of nonnegative values.

```python
# folds
levels = [0.1 ,0.2 ,0.3 ,1.1 ,1.2, 1.3]

reference = {'R_ACGH':0.1, ... }
problem = ROUProblem(model, levels=levels, reference= reference)
```
 

You may find additional information on the MEWpy documentation.

**Comment by Laminsecin** [comment]
@vmspereira Thanks a lot for your response.
