### ISSUE TITLE
The modules cannot be imported

### ISSUE THREAD

**Issue by revas** [BioSystemsUM/mewpy#5]
Hello. I installed mewpy through pip install- it installed the dependencies like cobra, but the modules for mewpy cannot be imported:

ModuleNotFoundError: No module named 'mewpy'

It is in my pip list, so I assume the problem's somewhere else?

This applies to all its modules, I reinstalled this package github, too, but it is not working yet.

**Comment by vmspereira** [comment]
Hi,

This is indeed very strange. 
Both the Pipy and Github versions have been adequately tested, as you may verify on the continuous integration badge. 
I would suggest that you install MEWpy in a new Python environment. 
Though I suggest using Python 3.7, you may use other Python versions (3.6 or 3.8) as long as you have a compatible commercial solver (CPLEX or GUROBI).

Let me know if you require additional help.

**Comment by revas** [comment]
Hi. Thanks so much for quick reply. I used the other Python versions, but they didn't help. Then I borrowed another system and it is working. So, the problem is from my side. Sorry for that!
By the way, I would like to use this opportunity to ask a few questions (I hope it is okay):

A) How does EA that MEWpy offers differ from the results predicted by gMCS? 
B) What is the optimisation algorithm for GOUProblem class and how different it is from OptKnock and OptGene? Is there any way to speed up its processing time? 

Thanks!

**Comment by vmspereira** [comment]
Hi,
I apologise for the late reply.
In response to your questions:

A) gMCS aims to find the minimal sets of genes whose simultaneous inhibition would render the functioning of a given metabolic task impossible. MEWpy may also be used to that end, if an adequate objective function is given which may be combined with other objective functions already made available (you may refer to the [MEWpy documentation](https://mewpy.readthedocs.io/en/latest/)).

B) The response to your question, regarding a GOUProblem, may also be found on the MEWpy documentation. There are several ways to speed up the heuristics. One obvious way is to use parallelization, by defining the number of available processors (threads). By default MEWpy uses half of the available processing power of the computer. Also, MEWpy may be used in a high performance computing cluster,  if available. You might also want to specify a reduced set of modification targets, in this case, a particular set of genes. This will reduce the dimension of the search space.  It is also possible to provide a set of initial solutions, guiding the search towards specific configurations, over which the heuristic will try to improve. You may find additional information to that mater on the documentation.
